### ISSUE TITLE
Does the Clinica ADNI-to-BIDS pipeline build field maps?

### ISSUE THREAD

**Issue by likeajumprope** [aramis-lab/clinica#1044]
**Description**
Hi, we are planning to use the ADNI to BIDS pipeline. We could not find any information on whether this pipeline includes the building of field maps. Does it?

**Pipeline**
Which Clinica's Pipeline is concerned?
- building of field maps

**Converters**
Which Clinica's converter is concerned?
- adni-to-bids

**I/O tools**
Which Clinica's tool is concerned?
NA

**Comment by vnckppl** [comment]
I am interested in this as well, specifically fMRI field maps, either GRE or AP/PA images that would then be stored in a BIDS compliant FMAP folder for use with (e.g.) fMRIprep later.

**Comment by NicolasGensollen** [comment]
Hi @likeajumprope 

The ADNI to BIDS pipeline doesn't currently convert field maps and I don't believe this was planned in our roadmap.
Depending on how much work it would be to include these in the conversion (and maintain the added code), we could consider implementing it.
In order to grasp this amount of work, could you specify your feature request in more details ? For example, on a specific example (subject XXX, session YYY) what are the input files that we would need and what would the output looks like.

**Comment by NicolasGensollen** [comment]
> Hello, our team is also interested in having this feature. I'm currently working on editing the code to address this issue. Has any work been done for this so far? If not, we may submit a pull request in the future.

Hi @tharpm95 
Nothing has been done on our side so far so feel free to go for it and open a PR.
Let me know if can help in the process.

**Comment by NicolasGensollen** [comment]
Thanks for the PR @tharpm95 ! 🙏
Will take a look asap.
