### ISSUE TITLE
Support for DKT atlas in pet-surface

### ISSUE THREAD

**Issue by PavanChaggar** [aramis-lab/clinica#1049]
Hi, 

Thanks so much for the package. 
Is it possible to summarise PET SUVR obtained from pet-surface on the DKT atlas with 83 regions, as opposed to Desikan atlas? 

[EDIT]: I was actually referring to an augmentation of the DKT atlas to include deep grey nuclei and brainstem.

**Comment by NicolasGensollen** [comment]
Hi @PavanChaggar 

Thanks for your interest in Clinica.
Could you provide a reference for the exact version of the atlas you are interested in ?
I will take a look at the PETSurface pipeline to see whether this could be integrated easily or not.

**Comment by PavanChaggar** [comment]
Hi @NicolasGensollen 

Thanks! Apologies, I made an error in my original post. The atlas I am referring to is actually an augmentation of the DKT atlas to include subcortical structures. I believe the appropriate references are [1](https://www.sciencedirect.com/science/article/pii/S0165027011005991?via=ihub) and [2](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0048121). 

The augmentation includes all of the cortical regions in the DKT atlas in addition to bilateral thalamus, pallidum, putamen, caudate, nucleus accumbens, hippocampus and amygdala and brainstem, all of which are already FreeSurfer defined regionns. 

Is it possible to add these regions into the FreeSurfer pipeline or to customise which FreeSurfer regions are included in the final output?

**Comment by NicolasGensollen** [comment]
Hi @PavanChaggar 

I took a look at the code of the `T1Freesurfer` and `PETSurface` pipelines since my last message. First of all, please note that the `PETSurface` pipeline uses outputs from the `T1Freesurfer` pipeline and Clinica expects that the user made it run beforehand.

At the moment, at the end of `PETSurface`, you get output statistics for two atlases (Desikan and Destrieux) because they are used by default by the FreeSurfer utilities that are wrapped by the `T1Freesurfer` pipeline. Clinica implements regexp rules to automatically grab the parcellation files produced by Freesurfer. For example:

https://github.com/aramis-lab/clinica/blob/da641c485db7dd3021bf5e9330b5916fbc5353dd/clinica/utils/input_files.py#L105-L109

The two atlases are even hardcoded in various places of the `PETSurface` pipeline, for example here:

https://github.com/aramis-lab/clinica/blob/da641c485db7dd3021bf5e9330b5916fbc5353dd/clinica/pipelines/pet_surface/pet_surface_utils.py#L1176-L1179

It is possible to use an option of the `T1Freesurfer` pipeline to specify alternative atlases. Here is a copy of a note in the `T1Freesurfer` documentation page:

"""
If you wish to obtain your results with another atlas, you can specify the option `-ap/--atlas_path` with the path to the atlas folder. Your atlas will need to be in FreeSurfer gcs format (e.g `hemisphere.atlasname_6p0.gcs`). The results will be stored in the same folder as the original results (additional files in labels, stats and regional measures).
"""

In theory, you only need the `gcs` file corresponding to the atlas that you want to use. Is it something that you have?

The next step would be to implement more flexibility in the way the `PETSurface` pipeline choses the atlases in order to allow user-defined parcellations.

An alternative "quick-and-dirty" way would be to change the regexp for the Desikan or Destrieux atlas such that they match your parcellation instead.

Hope this helps a bit.
Let me know if you have the atlas in `gcs` format and want to try running `PETSurface` with it.

**Comment by PavanChaggar** [comment]
Hi @NicolasGensollen 

Sorry for the late reply. I am still interested in this but just a bit preoccupied with my thesis. 

I have some .gcs files than I can try out. After my thesis I can also try to make a PR that makes the freesurfer segmentation more configurable, to e.g. include hippocampus, amygdala, thalamic nuclei etc. 

Thanks, 
Pavan

**Comment by NicolasGensollen** [comment]
Hi @PavanChaggar 

No worries, there is no rush.
Feel free to try using the `.gcs` files in the `T1Freesurfer` pipeline when you have the chance, and do not hesitate to ping me if you want to work on a PR.
