### ISSUE TITLE
A required clinical file of NIFD_to_BIDS converter doesn't exist!

### ISSUE THREAD

**Issue by Ya-Lin-Huang** [aramis-lab/clinica#122]
Hello, 
I followed the instructions on the webpage of clinica (http://www.clinica.run/doc/Converters/NIFD2BIDS/), and the files below are required to perform nifd_to_bids conversion. 
  - NIFD_Clinical_Data_2017_final_updated.xlsx 
  - idaSearch_<date>.csv
  - DataDictionary_NIFD_2017.10.18.xlsx 
The first two files can be downloaded from IDA (LONI Image & Data Archive), but the "DataDictionary_NIFD_2017.10.18.xlsx " file can not be found in IDA.  
(In the "Study Data" of IDA, the files I can download are "NIFD_Clinical_Data_2017_final_updated.xlsx " and "NIFD_Clinical_Data_20200724_updated.xlsx".)

Where can I get "DataDictionary_NIFD_2017.10.18.xlsx " file or how can I solve this issue?

Thank you for your assistance!

**Comment by alexandreroutier** [comment]
Hello @Ya-Lin-Huang,

Sorry for my late answer.

This file was downloaded a few years ago from IDA but, apparently, it has disappeared from the site. We will contact them so that this file comes back.

In the meantime, we uploaded a version here: https://aramislab.paris.inria.fr/files/data/databases/converters/DataDictionary_NIFD_2017.10.18.xlsx

We will make a pull request in order to temporarily download this file from our server.

Best,
Alexandre
