### ISSUE TITLE
adni_to_bids converter

### ISSUE THREAD

**Issue by PolinaDruzhinina** [aramis-lab/clinica#128]
I lose most of the subjects when converting to bids format. In the find_image_path (adni_utils.py) function at some point the Sequence values get corrupted due to path to images also broken. In compute_t1_paths (adni_t1.py) we get the values of Sequence from MPRAGEMETA.csv file , but before function adni1go2_image Sequence values are different.

[log.txt](https://github.com/aramis-lab/clinica/files/5260903/log.txt)

[t1_df.xlsx](https://github.com/aramis-lab/clinica/files/5260924/t1_df.xlsx)

**Comment by alexandreroutier** [comment]
Hello @PolinaDruzhinina,

Sorry for my late answer on the [forum](https://groups.google.com/g/clinica-user/c/pwArw4yqgLo/m/batFh104AQAJ) and here.

Some issues regarding `adni-2-bids` were raised by other users in the Google group or GitHub.

Could you tell me when you downloaded ADNI dataset and clinical data?

Since it makes long time we did not download ADNI database , I will download some samples of ADNI participants and latest version of clinical data. Based on your message, I will work with these subjects:
- `014_S_0519`
- `031_S_0773`
- `121_S_1350`

Regarding the "More than 60 days for corresponding timepoint.." message, I will investigate if this comes from some changes in ADNIMERGE or other files.

In the meantime, could you use the `tree` command (`sudo apt-get install tree` on Linux or `brew install tree` on Mac to get `tree`) on give me the content of the following commands
- `tree -d <ADNI_Raw_Data>/<ADNI_ID>` where `<ADNI_ID>` is `014_S_0519`, `031_S_0773` and `121_S_1350`.
- `tree -d <ADNI_BIDS>/<participant_id>` where `<participant_id>` is `sub-ADNI014S0519`, `sub-ADNI031S0773` and `sub-ADNI121S1350`.


Best,
Alex

**Comment by omar-rifai** [comment]
Hi there, 

Since this issue has been inactive for a while and without any further input from the OP, I will close it down. If you are still experiencing the problem, do not hesitate to ask a question on the forum or open a new issue.

Regards, 

Omar El Rifai
