### ISSUE TITLE
Installation for developer version: numpy can not be installed automatically

### ISSUE THREAD

**Issue by anbai106** [aramis-lab/clinica#168]
Hello Aramiseur,

**Describe the bug**
I am installing Clinica developer version on my two Ubuntu 18.04 machine, following the instructions here: https://aramislab.paris.inria.fr/clinica/docs/public/latest/Installation/
After running this step: **pip install -r requirements-dev.txt**
It gave error saying that: **ModuleNotFoundError: No module named 'numpy'** 

**To Reproduce**
1. Go to 'https://aramislab.paris.inria.fr/clinica/docs/public/latest/Installation/'
2. Click on 'Developer installation (Advanced)'
3. Scroll down to 'We suggest creating a custom Conda environment and installing Clinica inside it:'
4. Follow those steps...

**Expected behavior**
Installation without error.

**Screenshots**
![Screenshot from 2021-02-25 15-12-05](https://user-images.githubusercontent.com/16743978/109211424-34c66780-777c-11eb-89b8-8861a0fa1059.png)

**Desktop (please complete the following information):**
 - OS: [Ubunt 18.04]
 - Browser [chrome]
 - Version [18.04]

**Additional context**
I solved this error by manually install numpy: **conda install numpy**. It seems that when conda creates a new env, it does not install numpy.

**Comment by mdiazmel** [comment]
Hi Hao,

Thanks for reporting this error. In fact, this is a problem due to `nipy`. Developers of this package assume that `numpy` is installed by default by all users (which is certainly false). So, when pip solves the dependency tree, sometimes it tries to install `nipy` before installing `numpy` (something is wrong with the installation of nipy, probably their `setup.py` file) and the error shows up. We have `numpy` as dependency of Clinica in our `requirements.txt` file (also in our `setup.py` file). When installing as developer, it uses the former file but pip doesn't guarantee the order in which the packages will be installed (it depends on how the dependency tree is build).

I'll report the bug to nipy devs.

**Comment by mdiazmel** [comment]
To complete the previous answer, your solution, is for the moment, the right one: install `numpy` (via conda or pip) before running `pip install -r requirements.txt`.

**Comment by omar-rifai** [comment]
Hello there, 

As the problem seems to have been identified and addressed, I will now close this issue.
