### ISSUE TITLE
t1-freesurfer cannot recognize BIDS or CAPS directory 

### ISSUE THREAD

**Issue by anbai106** [aramis-lab/clinica#169]
**Describe the bug**
I am running t1-freesurfer pipeline: **clinica run t1-freesurfer $bids_directory $caps_directory -wd $working_directory -np $n_procs**

The caps_direction is an existing but empty directory. After launching the pipeline, clinica is checking if there are processed images in CAPS directory. Apparently, there is not. Function **def determine_caps_or_bids(input_dir):** then says that Clinica can not determine the **caps_directory** is CAPS or BIDS, if there is no subfolders starting with "sub-" or "groups". The pipeline stops here.

**Expected behavior**
The pipeline should know this is a CAPS directory since the **caps_directory** is a mandatory argument. 

**Screenshots**
![Screenshot from 2021-02-25 15-44-13](https://user-images.githubusercontent.com/16743978/109214833-4f9adb00-7780-11eb-8029-a2312974f7d3.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [Chrome]
 - Version [18.04]

My current workaround is to manually create a "groups" subfolder in the caps_directory.

**Comment by alexandreroutier** [comment]
Bonjour / Bonsoir Hao ;-)

Currently, if want you want to run any pipeline that will create a CAPS directory (for instance any `t1-*` pipeline), you have 2 options:
1) (the preferred one) Do not create empty CAPS folder, this will be automatically created by Clinica.
2) If you must create a CAPS directory, simply add a `subjects` folder inside it. This will be detected as a CAPS directory by the `determine_caps_or_bids` function.

@mdiazmel: maybe this function can change. Either:
1) Change the content of the exception message
2) Write a Warning message instead of an exception and assume that it is a CAPS folder. If this folder is empty for reading, Clinica will raise an error during `clinica_file_reader` & cie.

🤔

**Comment by anbai106** [comment]
@alexandreroutier T'as tjrs raison :)
I think the error message is not logic. If the default behavior is that the **caps_dir** is an non-existing folder, the message should point this out, instead of saying that Clinica can not find the folder is bids or caps.

**Comment by 14thibea** [comment]
I agree with @anbai106 
I had the same problem and I think that the message error should be more explicit, or even better that using an empty caps folder should not trigger this error (for example by automatically creating a `groups` or a `subjects` folder inside it).

**Comment by alexandreroutier** [comment]
Another issue from the forum: https://groups.google.com/g/clinica-user/c/WK4fNUEtEsg/m/63b4rJLhBQAJ

I have the feeling that this proposition:
> Write a Warning message instead of an exception and assume that it is a CAPS folder. If this folder is empty for reading, Clinica will raise an error during clinica_file_reader & cie.

would solve this issue.

**Comment by omar-rifai** [comment]
Replaced exception with warning in PR#[202](https://github.com/aramis-lab/clinica/pull/202)
