### ISSUE TITLE
Unable to find dcm2nii

### ISSUE THREAD

**Issue by arswitze** [aramis-lab/clinica#191]
Hello,

I am trying to use the adni-to bids converter but I am unable to find the 2016 version of mricron that contains dcm2nii. It is no longer on their github. Do you know of another way I could download this application so I can use the converter? (I am using MacOSX 10.15)

Thank you

**Comment by omar-rifai** [comment]
Hello, 

Can you please try the following link to access older versions of MRIcron https://github.com/neurolabusc/MRIcron/releases ?

Best Regards

**Comment by mdiazmel** [comment]
Hi,

You can also try to download it from [here](https://www.nitrc.org/frs/?group_id=152). Unzip `mricronmac.zip` file from the item "MRIcron 4/2011 Macintosh OSX", for example. Then you can copy the binary for `dcm2nii`.

Best,

**Comment by omar-rifai** [comment]
Hello, 

Without further input from the OP, I will mark this as solved.

Regards

**Comment by skent259** [comment]
I was having a similar issue, and the suggestion by @mdiazmel solved it for me.  It may be worth updating the error message

`[Error] Clinica could not find dcm2nii tool from MRIcron in your PATH environment: this can be downloaded from https://www.nitrc.org/frs/?group_id=152 (choose the 2016 version).`

because the given link doesn't have a 2016 version and the 2019 version, when installed, doesn't seem to resolve the issue.
