### ISSUE TITLE
adni-to-bids saves incorrect T1_paths.tsv image IDs in certain cases

### ISSUE THREAD

**Issue by Chengwei94** [aramis-lab/clinica#204]
I have downloaded the images and put in the format as specified in the tutorial. However, adni-to-bids is unable to find the path, when the image is present. (The problem may lie with 002? since the few subjects that I tried all didnt work) 
An example will be 
'No T1 image path found for subject 002_S_0295 in visit bl with image ID 45108' .

It works well with other subjects that dont start with 002. ( I have only tried 2-3 subjects).

**Comment by 14thibea** [comment]
Hi!
Could you please check that the corresponding path given in `conversion_info/t1_paths.tsv` exists in your file structure?

**Comment by Chengwei94** [comment]
The path does not exist in t1_paths. I found that it does not work on certain runs instead of certain object. 

These are the runs it does not work:

**Subject ID:** 002_S_0295

ImgId that did not work
45108
40966
64025
123685
150177

**Subject ID:** 002_S_0413

ImgId that did not work
45117
79122
60008
120917
149740

The rest of the runs manage to work. The ones that did not work happens to be of the sequence MPR__GradWarp__B1_Correction__N3.

The fMRI manage to work correctly

**Comment by 14thibea** [comment]
I guess the problem comes from the fact that preprocessed images are missing for these participants. Could you please try to download them again ticking all the boxes in the "Image Types" section (see below).

<img width="284" alt="Capture d’écran 2021-04-16 à 08 59 36" src="https://user-images.githubusercontent.com/9931663/114984493-15051300-9e92-11eb-90b7-c55f1de7e208.png">

**Comment by 14thibea** [comment]
And I agree that the last line in the documentation is strange... What do you think @nburgos ?

**Comment by nburgos** [comment]
Indeed, this does not seem very logical. Maybe it's because the QC is done on the image with the most extensive preprocessing, so we check that is passes the QC for that image, and we assume that if the QC passed for N3_scaled it means that the N3 image ok and that we can select it. Not sure why we do not want the scaling though.

**Comment by Chengwei94** [comment]
Thanks for the reply. I think that the problem lies in that the t1_paths.tsv barring the image paths is pre-generated no matter what the image input(I have tried with an empty dataset)  is although the documentation say otherwise as below. 

In the documentation , it says that 

-The first option is to look at which one has been further processed (preferred series). The last processing step is scaling. So we look for a ‘Processed’ image with its sequence name ending by ‘Scaled’ (preferred_processed_scan).
- If not found, we look for images with the previous processing step, N3 bias field correction. So we look for a - - - Processed image with its sequence name ending by N3m (preferred_processed_scan).
-If there is no N3 processed image, we can only use the original image (original_image)

I have downloaded some more pre-processed images that matches the sequence of the ones that ones that are present in the t1_paths.csv. The images are found, but the imageIDs are incorrect.

Example of an line of output generated from t1_paths.csv (The imageIDs are in bold)

002_S_0295 | m06 | ADNI1/GO Month 6 | MPR__GradWarp__B1_Correction__N3 | 2/11/2006 | 5726 | 21856 | **40966** | 1.5 | FALSE | FALSE | /home/zhongwc/ADNI/images/scripts/ADNI/002_S_0295/MPR__GradWarp__B1_Correction__N3/2006-11-02_08_16_44.0/S21856/ADNI_002_S_0295_MR_MPR__GradWarp__B1_Correction__N3_Br_20070219173703059_S21856_**I40965.**nii

I40966 is supposed to be MPR__GradWarp__B1_Correction__N3__Scaled but saved as MPR__GradWarp__B1_Correction__N3 in t1_paths.csv, therefore instead clinica found I40955 which is MPR__GradWarp__B1_Correction__N3

**Comment by 14thibea** [comment]
Yes!
Concerning the first problem: actually the image selection is not done based on the images that were downloaded, but on the metadata (.csv files).
This means that if in the CSV files we found that a Processed image is theoretically available, we will look for this one only, even if you only downloaded original images. This is why `t1_paths.tsv` is always generated even if there are no images available.

**Comment by omar-rifai** [comment]
Hello @Chengwei94,

If I can chime in with my two cents: I think the phrasing in the documentation is a bit unfortunate, but what I think is meant, is that the "scaled" images are never chosen.

Indeed, I believe the step: 

 >The first option is to look at which one has been further processed (preferred series). The last processing step is scaling. So we look for a ‘Processed’ image with its sequence name ending by ‘Scaled’ (preferred_processed_scan).

Is only a technical detail explaining that if we see a "scaled" image in the code, we are sure that we have one with N3_correction (that we want to keep).

**Comment by Chengwei94** [comment]
Hello @omar-rifai 

I think that the problem is that the imageId correspond to the scaled ones while the sequence correspond to the non-scaled ones in T1_paths.tsv. 
Right now, I am just downloading the imageId in the T1_paths.tsv so this becomes an issue for me. I think I can manually fix it though, but this can be fixed with the next update. Thanks!

**Comment by omar-rifai** [comment]
Noted. Will have a look at this asap. Thank you for pointing it out!

**Comment by omar-rifai** [comment]
Hi @Chengwei94, 

just a small update: I have been looking at the issue and unfortunately it doesn't look that there is a straightforward solution. Indeed, the reason the "scaled" imageID are entered in the t1_paths.tsv files is because these are the only IDs reported by ADNI in their meta files (when the images are processed up to that point).

One alternative would be to take the ID from the filename in the input folder but this would of course result in unhelpful t1_paths files if the images were not properly downloaded in the first place. 

I will be looking further into this and hopefully find a compromise that is suitable for your use.

Regards

**Comment by Chengwei94** [comment]
Hi @ omar-rifai, 

Thanks for the update. I managed to fix it for my use from editting the adni_t1.py file, to find for scaled as well instead of only 'N3' files (around line 272). Not sure if this will be a fix for the problem though. 

Another remark is that the adni-to-bids runs slower and slower when I am processing a large number of subjects. (A random guess might be the memory are not freed) (I dont have any benchmark for this, but I manage to overcome the problem by running small batches of subjects at a time for multiple times instead)

**Comment by omar-rifai** [comment]
Hi, 

Thank you for your feedback. Keeping "scaled" images instead of only "N3" processed [in the code](https://github.com/aramis-lab/clinica/blob/1a59756480019503b1a34284d279730183e48115/clinica/iotools/converters/adni_to_bids/adni_modalities/adni_t1.py#L272) would be one way around this.

 However, we had voluntarily decided not to do so, in an effort of homogeneity, as "scaled " images seem to have been abandoned in later releases of ADNI. 

Also thanks for the feedback on the running time. It is something worth investigating. Would you mind opening a new issue to that regard so that I can close this one?

Regards, 

Omar

**Comment by omar-rifai** [comment]
Without further input from OP, I'm closing this issue. For the performance problem please refer to [issue 257](https://github.com/aramis-lab/clinica/issues/257)
