### ISSUE TITLE
Migrate dcm2nii calls to dcm2niix

### ISSUE THREAD

**Issue by ghisvail** [aramis-lab/clinica#235]
`dcm2nii` is considered deprecated upstream and superseded by `dcm2niix` which is actively maintained. Besides, it's becoming very difficult to find a working binary release for OSX and it will likely never be ported to the new M1.  

See #234 for further context.

**Comment by mdiazmel** [comment]
This will be definitely a nice contribution!

From what I understand, images from one of the databases that Clinca process (AIBL, If I'm not wrong) were only able to be converted with this deprecated software, due to the old version of the dicom format in the original images. If there is a way to make the conversion with `dcm2niix` that allow us to override the `dcm2nii` dependency! There are maybe also some clues to see from the side of  [pydicom](https://pydicom.github.io/pydicom/stable/) that has been added as a Clinica's dependency recently

**Comment by ghisvail** [comment]
Thanks for the pieces of context 👍
