### ISSUE TITLE
Clean up Clinica logs

### ISSUE THREAD

**Issue by omar-rifai** [aramis-lab/clinica#259]
**Is your feature request related to a problem? Please describe.**
Currently, most of the pipeline outputs are printed on screen which results in very verbose and counterproductive output.

**Describe the solution you'd like**
Create logs to capture some of the current outputs and hierarchize the  information according to the different logging levels (c.f https://docs.python.org/3/howto/logging.html)

**Comment by ghisvail** [comment]
We need to have a rethink of our needs in terms of logging in general. Right now, it's all over the place between the console outputs with manual syntax coloring (*sigh*) and the `clinica.log` and `pypeline.log` files. Those should also be placed elsewhere than the current working directory, since write permissions by the user aren't guaranteed.

The verbosity argument is fair, and can be handled properly by correctly setting our logging channels up and using sensible defaults (such as logging warning severity or higher in the console for instance). Right now, we do the equivalent of dumping everything to the info channel with custom coloring based on the severity of the message, which is a red flag since we are mixing content and presentation concerns.

**Comment by omar-rifai** [comment]
Yes good points. My main questions for the moment is what to do with the the content of the current logs as they seem to be useful in very specific cases and both possibilities I see  (merging the logs with the current output of cprint or having separate logs for different purposes), seem to present both advantages and pitfalls.

**Comment by ghisvail** [comment]
Regarding the CLI, may I suggest to default to the `warning` level and provide:

- `-v / --verbose` to increase the verbosity to info and debug (if specified twice)
- `-q / --quiet` to restrict the verbosity to error and critical (if specified twice)

That's one of the accepted standards nowadays and arguably a better UX than specifying the name of the log level (which no one remembers anyway).

**Comment by 14thibea** [comment]
I have a request concerning freesurfer: the logs can be difficult to understand when it crashes.
First the user is invited to open .pklz files with `nipypecli crash`.
Then in this file it is written that more information is available at `path/to/subject/scripts/recon-all.log`, and if no working_dir was specified this path is in a temporary folder that may be deleted.
It could be more efficient to copy the file `recon-all.log` somewhere accessible? Or at the end of `clinica.log`?

**Comment by ghisvail** [comment]
@14thibea That's a nice piece of feedback :+1:

I think the question of how to integrate logs from third-party tools run with subprocess or nipype deserves its own thread. Could you please open a new issue with a bit more context, what solutions we have today and what outcome you may expect instead?
