### ISSUE TITLE
Default cprint messages are not displayed

### ISSUE THREAD

**Issue by alexandreroutier** [aramis-lab/clinica#363]
**Describe the bug**
Default `cprint` callls are not displayed unless the `--verbose` is used:

<img width="1280" alt="t1-freesurfer-no-verbose" src="https://user-images.githubusercontent.com/24808663/127912723-d22ade99-2444-4315-974f-a0fe3d063f41.png">

<img width="1280" alt="t1-freesurfer-verbose" src="https://user-images.githubusercontent.com/24808663/127912912-46037341-0bda-4632-9d48-dd7b976a6f8d.png">

This has now changed. I would think that `INFO` level should be the displayed

**Expected behavior**
See for instance screenshots in https://github.com/aramis-lab/clinica/pull/58

**Comment by ghisvail** [comment]
The current bahavior is:

- Default `cprint` calls log messages to `INFO` unless a different channel is specified.

- Clinica displays messages of severity `WARNING` and above unless additional verbosity is requested with `-v` or `-vv`.

This behavior is intended to reduce default verbosity to an acceptable level, whilst allowing users to get more detailed output when necessary. Some adjustments to previous `cprint` calls were made to route messages to their appropriate channels based on their content. Despite that, feel free to submit a PR if you find any calls which severity should be promoted or downgraded.

**Comment by alexandreroutier** [comment]
The initial purpose of `cprint` was to display any message used with  `cprint` and hide any Third party print / warning / logger when `-v` is not triggered. In particular, when using `-v` option, you can notice that Nipype is too much verbose and does not contain easy-to-read information for the Clinica user.

In the end, even though it was not very pythonic - I totally agree on that, any pipeline had to display the following information when `-v` was not triggered:

- Number of images to process with their IDs
- Estimation of computational time per thread
- One line when an image / group of images (e.g. template or longitudinal) will be process
- One line when it's over
- Any Warning displayed with `cprint` (still not using a pythonic way)
(And for "chained pipelines" (e.g. `t1-volume` or `t1-freesurfer-longitudinal`), extra information regarding the sub-pipelines)
See for instance what we had in PR #58:
![t1-freesurfer](https://user-images.githubusercontent.com/24808663/74757893-e633e280-5276-11ea-82b1-ce6a50287e27.png)

Now, when running Clinica, we only have warning messages. I believe that Clinica should display `WARNING` level messages for third party apps and `INFO` for `cprint` calls. 

Sorry to insist on that but I am convinced that current outputs console with `clinica run` is now lacking useful information for the user.

Alexandre

**Comment by ghisvail** [comment]
> it was not very pythonic - I totally agree on that

Which is now fixed using the `logging` module and appropriate redirection.

Now we can improve on the content with feedback and suggestions. Moving on.

> any pipeline had to display the following information when -v was not triggered:
>
>    Number of images to process with their IDs
>    Estimation of computational time per thread
>    One line when an image / group of images (e.g. template or longitudinal) will be process
>    One line when it's over
>    Any Warning displayed with cprint (still not using a pythonic way)
>    (And for "chained pipelines" (e.g. t1-volume or t1-freesurfer-longitudinal), extra information regarding the sub-pipelines)

I could not find this specification back when I initially tackled the log situation. Thank you for taking the time to properly formalise it.

Now moving forward, to implement this we'd have to:
- Default logging to `INFO` instead of `WARNING`
- Provide only one level of verbosity (`INFO` -> `DEBUG`) instead of two
- Adjust the verbosity level of the `cprint` calls _not_ listed above to `DEBUG`. That's gonna be the most mechanical and time-consuming part of the code changes.

> I believe that Clinica should display WARNING level messages for third party apps and INFO for cprint calls.

Is everyone happy with the proposed default behavior? cc @mdiazmel @omar-rifai

**Comment by omar-rifai** [comment]
Hi @alexandreroutier, thanks for the feedback! Indeed we did not have this information when refactoring the code. For me the most urgent change is:

move third party party print / warning / logger away from the legacy "Clinica cprint" messages. This would correspond to point 3 specified above by @ghisvail.

If that is implemented, we would have all the relevant info you mention (-v option: Number of images to process with their IDs
Estimation of computational time per thread, etc...) separated from Nipype's verbose outputs (-vv option).

For the remaining two changes, I'm a bit mitigated (But not against the idea completly, I just want to understand better, since the default to WARNING seems naturally intuitive to me).

- Default logging to INFO instead of WARNING
- Provide only one level of verbosity (INFO -> DEBUG) instead of two

Is there specific reason why we would want them to be printed by default instead of the "info" level?

**Comment by omar-rifai** [comment]
Opened associated [discussion](https://github.com/aramis-lab/clinica/discussions/457) to exchange ideas.
