### ISSUE TITLE
Fix PET entity names in converters

### ISSUE THREAD

**Issue by omar-rifai** [aramis-lab/clinica#592]
Both in `ADNI` and `AIBL`, the current use of the `acq` entity must be replaced with the [bids-compliant](https://bids-specification.readthedocs.io/en/stable/99-appendices/09-entities.html#trc) `trc` keyword.

**Comment by alexandreroutier** [comment]
Hi!

Does this mean that intputs/outputs for `pet-volume` and `pet-surface*` pipelines will also be updated? This would also affect intputs for `statistics-volume` and `statistics-surface` pipeline.

Since 1.6.0 release of BIDS with addition of PET imaging data (BEP 9), this would mean that both pipelines and converters should be updated to comply with final naming convention.

From what I understand, we had in Clinica:
```text
sub-<label>[_ses-<label>]_task-rest_acq-<label>_pet.nii.gz
```
which followed BEP 9 naming convention before its final versions. And now, this would be:
```text
sub-<label>[_ses-<label>]_trc-<label>_pet.nii.gz
```
in order to comply with BIDS >= 1.6.0.

Alexandre
