### ISSUE TITLE
[PET] Improve how to 4D images with 1 volume are handled

### ISSUE THREAD

**Issue by alexandreroutier** [aramis-lab/clinica#871]
Hi!

Following Discussion https://github.com/aramis-lab/clinica/discussions/870, it turns out that 4D images with 1 volume are not taken into account in PET pipelines:

- `pet-surface*`:
https://github.com/aramis-lab/clinica/blob/4e5f5d93f7629d726e4efc6a70ee16c603d62dab/clinica/pipelines/pet_surface/pet_surface_utils.py#L949-L952

- `pet-volume*`:
https://github.com/aramis-lab/clinica/blob/4e5f5d93f7629d726e4efc6a70ee16c603d62dab/clinica/pipelines/pet_volume/pet_volume_utils.py#L13-L16

A solution would be:
```python
    if len(img.shape) == 4:
        if img.shape[3] > 1:
            error_msg = (
                f"Clinica does not handle 4D volumes for {image_id.replace('_', ' | ')}"
            )

```
(I have a doubt but a oneliner `if len(img.shape) == 4 and img.shape[3] > 1:` could also work)

Best,
Alex

**Comment by NicolasGensollen** [comment]
Thanks for looking into this @alexandreroutier !
I'm wondering whether we should also explicitly squeeze the image in this case (might be done automatically by tools downstream, but doesn't hurt I think...). Maybe something like this:

```python
def _check_img_3d(img):
    """Load a 3D nifti image, raise if not 3D...""" 
    img = nib.load(img)
    dim = len(img.shape) 
    if dim != 3:
        if dim == 4 and img.shape[3] == 1:
            data = img.get_fdata()
            klass = img.__class__
            header = copy.deepcopy(img.header)
            return klass(data[:, :, :, 0], img.affine, header=header)
        error_msg = ( 
             f"Clinica does not handle {dim}D volumes for {image_id.replace('_', ' | ')}" 
         ) 
        cprint(error_msg, lvl="error")
        raise NotImplementedError(error_msg)
    return img
```

**Comment by ghisvail** [comment]
>  I'm wondering whether we should also explicitly squeeze the image in this case 

In that case, I'd suggest to rename this function to something more explicit. `check` implies a boolean or exception raising function. Here we are actually loading and returnung the data.

> (might be done automatically by tools downstream, but doesn't hurt I think...).

From the old `nipype` code base perpsective, I think you are right.

For the `pydra` pipelines, since they rely on checksumming the input files to handle caching, the 4D to 3D squeezing should probably happen in a separate node which will keep track of the old and new (squeezed) volume files.

On a side note, since the PET volumes likely came from preprocessed ADNI files, maybe it's also the job of our converters to ensure volumes are squeezed and (re)written to 3D. There was also a similar point raised in #622 about normalizing  the data type used for writing.

**Comment by NicolasGensollen** [comment]
> In that case, I'd suggest to rename this function to something more explicit. `check` implies a boolean or exception raising function. Here we are actually loading and returnung the data.

Yes, I agree the name is misleading, I'll change that in #872

**Comment by alexandreroutier** [comment]
I didn't think about it yesterday but you are raising the fact that we don't known how third party apps are handling this particular case 🤔 Generating an 'adequate' 3D image would be the simplest solution.

(For info, this `NotImplementedError` was added in order to solve https://github.com/aramis-lab/clinica/issues/70)
